# GitHub Secret Scanning Configuration for Amplifi
# This file helps GitHub understand which files contain safe public keys

# Firebase API keys in web applications are public client-side keys
# They are designed to be exposed and cannot be used to access the backend
# without proper authentication and domain restrictions

# Files that contain public client-side keys (safe to expose)
public_keys:
  - public/firebaseConfig.js
  - public/app.js

# Files that should be scanned for actual secrets
secret_files:
  - .env
  - .env.local
  - .env.production
  - firebase-service-account.json
  - stripe-secret-key.txt

# Ignore patterns for public client-side keys
ignore_patterns:
  - "AIzaSy[A-Za-z0-9_-]{35}"  # Firebase API keys (public client-side)
  - "ca-pub-[0-9]{16}"         # AdMob publisher IDs (public)
  - "pk_test_[A-Za-z0-9]{24}"  # Stripe test publishable keys (public)
  - "pk_live_[A-Za-z0-9]{24}"  # Stripe live publishable keys (public)

# Actual secret patterns to detect
secret_patterns:
  - "sk_test_[A-Za-z0-9]{24}"  # Stripe test secret keys
  - "sk_live_[A-Za-z0-9]{24}"  # Stripe live secret keys
  - "firebase-adminsdk"         # Firebase service account keys
  - "-----BEGIN PRIVATE KEY-----"  # Private keys 